apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl:
    manifests: 
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: abhishekrs77/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: abhishekrs77/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '**/*.ts'
            dest: .
    - image: abhishekrs77/tokens
      context: tokens
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: abhishekrs77/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: . 
    - image: abhishekrs77/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: . 
    - image: abhishekrs77/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: . 