name: deploy-tokens

on:
  push:
    branches:
      - master
    paths:
      - 'tokens/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tokens && docker build -t abhishekrs77/tokens .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push abhishekrs77/tokens