name: tests-tokens

on: 
  pull_request:
    paths:
      - 'tokens/**'
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd tokens && npm install && npm run test:ci
